DAY = 'day'
ORDER_ID = 'order_id'
ITEM_DETAIL_INFO = 'item_det_info'
PAY_TIMESTAMP = 'pay_timestamp'
BUYER_ID = 'buyer_id'
PROMISE_SPEED = 'promise_speed'
IF_CAINIAO = 'if_cainiao'
MERCHANT_ID = 'merchant_id'
LOGISTICS_REVIEW_SCORE = 'logistics_review_score'

PAY_TIMESTAMP_DATETIME = 'pay_timestamp_datetime'
