name: capstone
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - matplotlib
  - jupyterlab
  - pytorch
  - torchtext
  - pandas
  - pyarrow
  - seaborn
  - scipy
  - statsmodels
  - scikit-learn
#  - pip:
#    - torchviz